{
  "openapi": "3.1.0",
  "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
  "info": {
    "title": "Ani",
    "version": "1.0.0",
    "description": "Ani API"
  },
  "servers": [
    {
      "url": "https://danmaku.api.myani.org/"
    }
  ],
  "paths": {
    "/v1/danmaku/{episodeId}": {
      "get": {
        "tags": [],
        "summary": "获取弹幕",
        "description": "获取某一剧集内的弹幕，可指定某一时间范围及最大获取数量。",
        "parameters": [
          {
            "name": "episodeId",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "description": "剧集ID",
            "required": true,
            "deprecated": false
          },
          {
            "name": "maxCount",
            "in": "query",
            "schema": {
              "type": "number",
              "format": "int32"
            },
            "description": "最大弹幕获取数量，默认为8000",
            "required": false,
            "deprecated": false
          },
          {
            "name": "fromTime",
            "in": "query",
            "schema": {
              "type": "number",
              "format": "int64"
            },
            "description": "过滤范围开始时间，单位为毫秒，默认为0",
            "required": false,
            "deprecated": false
          },
          {
            "name": "toTime",
            "in": "query",
            "schema": {
              "type": "number",
              "format": "int64"
            },
            "description": "过滤范围结束时间，单位为毫秒，默认为-1；值为负数时表示不限制结束时间",
            "required": false,
            "deprecated": false
          }
        ],
        "responses": {
          "200": {
            "description": "弹幕列表",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DanmakuGetResponse"
                },
                "examples": {
                  "": {
                    "value": {
                      "danmakuList": [
                        {
                          "id": "ba1f213a-50bd-4e09-a4e0-de6e24b72e22",
                          "senderId": "3db414d0-930a-4144-84cf-b841f486215e",
                          "danmakuInfo": {
                            "playTime": 0,
                            "color": -16777216,
                            "text": "Hello, world!",
                            "location": "NORMAL"
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "451": {
            "description": "请求弹幕数量过多。maxCount参数传入值超过8000时会返回此错误。",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [],
        "summary": "发送弹幕",
        "description": "发送一条弹幕至某一剧集，可指定弹幕时间、内容、颜色和内容。需要用户登录。",
        "parameters": [
          {
            "name": "episodeId",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "description": "剧集ID",
            "required": true,
            "deprecated": false
          }
        ],
        "requestBody": {
          "description": "弹幕信息",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DanmakuPostRequest"
              },
              "examples": {
                "": {
                  "value": {
                    "danmakuInfo": {
                      "playTime": 0,
                      "color": -16777216,
                      "text": "Hello, world!",
                      "location": "NORMAL"
                    }
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "弹幕发送成功",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "401": {
            "description": "未登录或用户token无效",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "441": {
            "description": "弹幕内容为空",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "auth-jwt": []
          }
        ]
      },
      "parameters": []
    },
    "/v1/login/bangumi": {
      "post": {
        "tags": [],
        "summary": "使用Bangumi token登录",
        "description": "使用Bangumi token登录并获取用户会话token。",
        "parameters": [],
        "requestBody": {
          "description": "Bangumi token字符串",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BangumiLoginRequest"
              },
              "examples": {
                "": {
                  "value": {
                    "bangumiToken": "VAcbHKhXqcjpCOVY5KFxwYEeQCOw4i0u",
                    "clientVersion": "3.0.0-beta24",
                    "clientOS": "Android",
                    "clientArch": "aarch64"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "用户会话token字符串",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BangumiLoginResponse"
                },
                "examples": {
                  "": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJIZWxsbyB0aGVyZSJ9.TNpICIfOzK-BvxxV72ApTiD4SlAwvzHbu_0O3FXq-s4"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Bangumi token无效",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "461": {
            "description": "请求体中客户端版本无效",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/v1/me": {
      "get": {
        "tags": [],
        "summary": "查看当前用户信息",
        "description": "查看当前携带的token对应用户的信息，包含其Ani ID，Bangumi昵称以及Bangumi头像URL。",
        "parameters": [],
        "responses": {
          "200": {
            "description": "用户信息",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AniUser"
                },
                "examples": {
                  "": {
                    "value": {
                      "id": "762e10b5-37c2-4a2b-a39b-b3033a5979f8",
                      "nickname": "Him188",
                      "smallAvatar": "https://example.com/avatarSmall.jpg",
                      "mediumAvatar": "https://example.com/avatarMedium.jpg",
                      "largeAvatar": "https://example.com/avatarLarge.jpg",
                      "registerTime": 1714404248957,
                      "lastLoginTime": 1714404248957,
                      "clientVersion": "3.0.0-beta22",
                      "clientPlatforms": [
                        "macos-aarch64",
                        "android-aarch64",
                        "windows-x86_64"
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "未登录或用户token无效",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "404": {
            "description": "用户token对应的用户不存在",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [
          {
            "auth-jwt": []
          }
        ]
      },
      "parameters": []
    },
    "/v1/updates/incremental": {
      "get": {
        "tags": [],
        "summary": "获取可更新的版本号列表",
        "description": "返回所有大于当前版本的更新版本号。",
        "parameters": [
          {
            "name": "clientVersion",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "客户端当前版本号。不合法的版本号会导致服务器返回461 Invalid Client Version错误。",
            "required": true,
            "deprecated": false
          },
          {
            "name": "clientPlatform",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "客户端平台，例：windows, android。不合法的值会导致服务器返回空的版本号列表。",
            "required": true,
            "deprecated": false
          },
          {
            "name": "clientArch",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "客户端架构，例：x86_64, aarch64。不合法的值会导致服务器返回空的版本号列表。",
            "required": true,
            "deprecated": false
          },
          {
            "name": "releaseClass",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "更新版本的发布类型，可选值：alpha, beta, rc, stable。不合法的发布类型会导致服务器返回400 Bad Request错误。",
            "required": true,
            "deprecated": false
          }
        ],
        "responses": {
          "200": {
            "description": "更新版本号列表",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReleaseUpdatesResponse"
                },
                "examples": {
                  "": {
                    "value": {
                      "versions": [
                        "3.0.0-rc01",
                        "3.0.0-rc02",
                        "3.0.0-rc03"
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "461": {
            "description": "不合法的客户端版本号",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/v1/updates/incremental/details": {
      "get": {
        "tags": [],
        "summary": "获取可更新的版本详情",
        "description": "返回所有大于当前版本的更新版本的详细信息，包括版本号、下载地址、发布时间以及更新内容。",
        "parameters": [
          {
            "name": "clientVersion",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "客户端当前版本号。不合法的版本号会导致服务器返回461 Invalid Client Version错误。",
            "required": true,
            "deprecated": false
          },
          {
            "name": "clientPlatform",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "客户端平台，例：windows, android。不合法的值会导致服务器返回空的版本号列表。",
            "required": true,
            "deprecated": false
          },
          {
            "name": "clientArch",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "客户端架构，例：x86_64, aarch64。不合法的值会导致服务器返回空的版本号列表。",
            "required": true,
            "deprecated": false
          },
          {
            "name": "releaseClass",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "description": "更新版本的发布类型，可选值：alpha, beta, rc, stable。不合法的发布类型会导致服务器返回400 Bad Request错误。",
            "required": true,
            "deprecated": false
          }
        ],
        "responses": {
          "200": {
            "description": "更新版本详细信息列表",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReleaseUpdatesResponse"
                },
                "examples": {
                  "": {
                    "value": {
                      "updates": [
                        {
                          "version": "3.0.0-rc01",
                          "downloadUrlAlternatives": [
                            "https://d.myani.org/v3.0.0-rc01/ani-3.0.0-rc01.apk"
                          ],
                          "publishTime": 1716604732,
                          "description": "## 主要更新\n- 重新设计资源选择器 #328\n   - 了解每个数据源的查询结果, 失败时点击重试 #327 #309\n   - 支持临时启用禁用数据源以应对未找到的情况\n   - 区分 BT 源和在线源并增加提示 #330\n- 优化资源选择算法\n  - 默认隐藏生肉资源, 可在设置中恢复显示\n  - 支持番剧完结后隐藏单集 BT 资源, 默认启用, 可在设置关闭\n  - 支持优先选择季度全集资源 #304\n  - 自动优先选择本地缓存资源, 不再需要等待 #258 #260\n## 次要更新\n- 提高弹幕匹配准确率 #338\n- 自动选择数据源时不再覆盖偏好设置\n- 自动选择数据源时不再保存不准确的字幕语言设置\n- 在切换数据源时, 将会按顺序自动取消筛选直到显示列表不为空\n- 在取消选择数据源的过滤时也记忆偏好设置\n- 修复有时候选择资源时会崩溃的问题\n- 优化数据源请求时的性能\n- 修复标题过长挤掉按钮的问题 #311\n- 修复会请求过多条目的问题\n- 修复条目缓存页可能有资源泄露的问题 #190"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          },
          "461": {
            "description": "不合法的客户端版本号",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Any"
                }
              }
            }
          }
        },
        "deprecated": false
      },
      "parameters": []
    }
  },
  "webhooks": {

  },
  "components": {
    "schemas": {
      "Any": {
        "type": "object",
        "properties": {

        },
        "required": []
      },
      "DanmakuPostRequest": {
        "type": "object",
        "properties": {
          "danmakuInfo": {
            "$ref": "#/components/schemas/DanmakuInfo"
          }
        },
        "required": [
          "danmakuInfo"
        ]
      },
      "DanmakuInfo": {
        "type": "object",
        "properties": {
          "color": {
            "type": "number",
            "format": "int32"
          },
          "location": {
            "$ref": "#/components/schemas/DanmakuLocation"
          },
          "playTime": {
            "type": "number",
            "format": "int64"
          },
          "text": {
            "type": "string"
          }
        },
        "required": [
          "color",
          "location",
          "playTime",
          "text"
        ]
      },
      "DanmakuLocation": {
        "type": "string",
        "enum": [
          "TOP",
          "BOTTOM",
          "NORMAL"
        ]
      },
      "DanmakuGetResponse": {
        "type": "object",
        "properties": {
          "danmakuList": {
            "items": {
              "$ref": "#/components/schemas/Danmaku"
            },
            "type": "array"
          }
        },
        "required": [
          "danmakuList"
        ]
      },
      "Danmaku": {
        "type": "object",
        "properties": {
          "danmakuInfo": {
            "$ref": "#/components/schemas/DanmakuInfo"
          },
          "id": {
            "type": "string"
          },
          "senderId": {
            "type": "string"
          }
        },
        "required": [
          "danmakuInfo",
          "id",
          "senderId"
        ]
      },
      "BangumiLoginResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        },
        "required": [
          "token"
        ]
      },
      "BangumiLoginRequest": {
        "type": "object",
        "properties": {
          "bangumiToken": {
            "type": "string"
          },
          "clientArch": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "string"
              }
            ]
          },
          "clientOS": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "string"
              }
            ]
          },
          "clientVersion": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "string"
              }
            ]
          }
        },
        "required": [
          "bangumiToken"
        ]
      },
      "AniUser": {
        "type": "object",
        "properties": {
          "clientPlatforms": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "clientVersion": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "string"
              }
            ]
          },
          "id": {
            "type": "string"
          },
          "largeAvatar": {
            "type": "string"
          },
          "lastLoginTime": {
            "type": "number",
            "format": "int64"
          },
          "mediumAvatar": {
            "type": "string"
          },
          "nickname": {
            "type": "string"
          },
          "registerTime": {
            "type": "number",
            "format": "int64"
          },
          "smallAvatar": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "largeAvatar",
          "lastLoginTime",
          "mediumAvatar",
          "nickname",
          "registerTime",
          "smallAvatar"
        ]
      },
      "ReleaseUpdatesResponse": {
        "type": "object",
        "properties": {
          "versions": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "versions"
        ]
      }
    },
    "securitySchemes": {
      "auth-jwt": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [],
  "tags": []
}